import { DEFAULT_PARAMS, Patch, Multi, Setlist } from "../types";

// DURAN DURAN CLASSIC SIGNATURE PATCHES
export const DURAN_PATCHES: Patch[] = [
  // 1. RIO (4 Patches)
  {
    id: "duran-rio-bass",
    name: "Rio Drive Bass",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vco2Waveform: "square",
      vco1Range: 16,
      vco2Range: 16,
      vco2Detune: 0.1,
      vcoMix: 0.5,
      mixerVco1: 1.0,
      mixerVco2: 0.9,
      filterCutoff: 150,
      filterResonance: 0.25,
      filterEnvAmount: 0.7,
      env1Attack: 0.001,
      env1Decay: 0.22,
      env1Sustain: 0.1,
      env1Release: 0.15,
      env2Attack: 0.001,
      env2Decay: 0.35,
      env2Sustain: 0.8,
      env2Release: 0.2,
      chorusMix: 0.25,
      compMix: 0.7
    }
  },
  {
    id: "duran-rio-arp",
    name: "Rio Fast Arp",
    params: {
      ...DEFAULT_PARAMS,
      arpEnabled: true,
      arpMode: "random",
      arpRate: 160,
      arpRange: 2,
      vco1Waveform: "sawtooth",
      vcoMix: 0.0,
      mixerVco1: 1.0,
      filterCutoff: 850,
      filterResonance: 0.45,
      filterEnvAmount: 0.35,
      env1Attack: 0.001,
      env1Decay: 0.15,
      env2Attack: 0.001,
      env2Decay: 0.12,
      env2Sustain: 0.0,
      delayMix: 0.45,
      delayTime: 0.375,
      delayFeedback: 0.5,
      chorusMix: 0.3
    }
  },
  {
    id: "duran-rio-strings",
    name: "Rio Jupiter Pad",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vco2Waveform: "sawtooth",
      vco1Range: 8,
      vco2Range: 8,
      vco2Detune: 0.22,
      vcoMix: 0.5,
      mixerVco1: 0.85,
      mixerVco2: 0.85,
      filterCutoff: 1100,
      filterResonance: 0.1,
      filterEnvAmount: 0.4,
      filterKeyboardTrack: 0.9,
      env1Attack: 0.5,
      env1Decay: 1.8,
      env1Sustain: 0.85,
      env1Release: 1.8,
      env2Attack: 0.35,
      env2Decay: 1.8,
      env2Sustain: 0.95,
      env2Release: 1.8,
      chorusMix: 0.88,
      chorusMode: 3,
      reverbMix: 0.55,
      reverbTime: 4.2
    }
  },
  {
    id: "duran-rio-brass",
    name: "Rio Brass Stab",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vco2Waveform: "sawtooth",
      vco1Range: 8,
      vco2Range: 8,
      vco2Detune: 0.18,
      subOscEnabled: true,
      subOscMix: 0.2,
      vcoMix: 0.5,
      mixerVco1: 1.0,
      mixerVco2: 1.0,
      filterCutoff: 380,
      filterResonance: 0.22,
      filterEnvAmount: 0.82,
      env1Attack: 0.10,
      env1Decay: 0.75,
      env1Sustain: 0.35,
      env1Release: 0.45,
      env2Attack: 0.015,
      env2Decay: 0.9,
      env2Sustain: 0.8,
      env2Release: 0.45,
      chorusMix: 0.6,
      chorusMode: 2,
      reverbMix: 0.35,
      reverbTime: 3.0
    }
  },

  // 2. HUNGRY LIKE THE WOLF (4 Patches)
  {
    id: "duran-wolf-bass",
    name: "Wolf Punch Bass",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vco2Waveform: "sawtooth",
      vco1Range: 16,
      vco2Range: 16,
      vco2Detune: 0.14,
      vcoMix: 0.5,
      mixerVco1: 1.0,
      mixerVco2: 1.0,
      filterCutoff: 180,
      filterResonance: 0.15,
      filterEnvAmount: 0.6,
      env1Attack: 0.001,
      env1Decay: 0.25,
      env1Sustain: 0.2,
      env1Release: 0.15,
      env2Attack: 0.001,
      env2Decay: 0.3,
      env2Sustain: 0.75,
      env2Release: 0.15,
      chorusMix: 0.3,
      compMix: 0.75
    }
  },
  {
    id: "duran-wolf-arp",
    name: "Wolf Rhythmic Arp",
    params: {
      ...DEFAULT_PARAMS,
      arpEnabled: true,
      arpMode: "up-down",
      arpRate: 145,
      arpRange: 2,
      vco1Waveform: "pulse",
      vco1PulseWidth: 0.25,
      vcoMix: 0.0,
      mixerVco1: 1.0,
      filterCutoff: 1100,
      filterResonance: 0.35,
      filterEnvAmount: 0.4,
      env1Attack: 0.001,
      env1Decay: 0.14,
      env2Attack: 0.001,
      env2Decay: 0.1,
      env2Sustain: 0.0,
      delayMix: 0.4,
      delayTime: 0.25,
      delayFeedback: 0.4,
      chorusMix: 0.25
    }
  },
  {
    id: "duran-wolf-pad",
    name: "Wolf Backing Pad",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vco2Waveform: "triangle",
      vco1Range: 8,
      vco2Range: 8,
      vco2Detune: 0.15,
      vcoMix: 0.4,
      mixerVco1: 0.8,
      mixerVco2: 0.8,
      filterCutoff: 650,
      filterResonance: 0.05,
      env1Attack: 0.6,
      env1Decay: 2.0,
      env1Sustain: 0.85,
      env1Release: 1.8,
      env2Attack: 0.5,
      env2Decay: 2.0,
      env2Sustain: 0.9,
      env2Release: 1.8,
      chorusMix: 0.75,
      reverbMix: 0.4
    }
  },
  {
    id: "duran-wolf-lead",
    name: "Wolf Sync Lead",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vco2Waveform: "sawtooth",
      vco2Sync: true,
      vco2Freq: 3.5,
      vcoMix: 0.3,
      mixerVco1: 1.0,
      mixerVco2: 1.0,
      filterCutoff: 2500,
      filterResonance: 0.25,
      filterEnvAmount: 0.7,
      env1Attack: 0.01,
      env1Decay: 0.4,
      env1Sustain: 0.5,
      env1Release: 0.3,
      env2Attack: 0.005,
      env2Decay: 0.6,
      env2Sustain: 0.9,
      env2Release: 0.3,
      distortionMix: 0.35,
      distortionAmount: 0.4,
      delayMix: 0.3,
      delayTime: 0.33
    }
  },

  // 3. SAVE A PRAYER (4 Patches)
  {
    id: "duran-prayer-bass",
    name: "Prayer Warm Bass",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vco2Waveform: "sine",
      vco1Range: 16,
      vco2Range: 16,
      vcoMix: 0.3,
      mixerVco1: 0.85,
      mixerVco2: 1.0,
      filterCutoff: 130,
      filterResonance: 0.1,
      filterEnvAmount: 0.45,
      env1Attack: 0.002,
      env1Decay: 0.3,
      env1Sustain: 0.3,
      env1Release: 0.25,
      env2Attack: 0.001,
      env2Decay: 0.4,
      env2Sustain: 0.9,
      env2Release: 0.25,
      chorusMix: 0.2
    }
  },
  {
    id: "duran-prayer-arp",
    name: "Prayer Echo Arp",
    params: {
      ...DEFAULT_PARAMS,
      arpEnabled: true,
      arpMode: "up",
      arpRate: 195,
      arpRange: 3,
      vco1Waveform: "pulse",
      vco1PulseWidth: 0.3,
      vcoMix: 0.0,
      mixerVco1: 0.85,
      filterCutoff: 1400,
      filterResonance: 0.25,
      filterEnvAmount: 0.5,
      env1Attack: 0.002,
      env1Decay: 0.22,
      env2Attack: 0.001,
      env2Decay: 0.15,
      env2Sustain: 0.0,
      delayMix: 0.6,
      delayTime: 0.45,
      delayFeedback: 0.6,
      chorusMix: 0.4,
      reverbMix: 0.45
    }
  },
  {
    id: "duran-prayer-pad",
    name: "Prayer Dreamy Pad",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "triangle",
      vco2Waveform: "sine",
      vco2Detune: 0.15,
      vcoMix: 0.5,
      mixerVco1: 0.9,
      mixerVco2: 0.9,
      filterCutoff: 500,
      filterResonance: 0.2,
      env1Attack: 1.5,
      env1Decay: 2.5,
      env1Sustain: 0.85,
      env1Release: 2.5,
      env2Attack: 1.2,
      env2Decay: 2.2,
      env2Sustain: 0.9,
      env2Release: 2.5,
      chorusMix: 0.8,
      chorusMode: 3,
      reverbMix: 0.75,
      reverbTime: 5.0
    }
  },
  {
    id: "duran-prayer-lead",
    name: "Prayer Ocarina/Flute",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sine",
      vco2Waveform: "triangle",
      vco1Range: 4,
      vco2Range: 4,
      vco2Detune: 0.04,
      vcoMix: 0.35,
      mixerVco1: 1.0,
      mixerVco2: 0.7,
      portamentoMode: "on",
      portamentoTime: 0.18,
      filterCutoff: 1800,
      filterResonance: 0.08,
      filterKeyboardTrack: 1.0,
      env2Attack: 0.06,
      env2Decay: 1.2,
      env2Sustain: 0.85,
      env2Release: 0.6,
      vcoLfoAmount: 0.05,
      lfoRate: 5.2,
      lfoDelay: 0.2,
      reverbMix: 0.55,
      reverbTime: 4.5,
      delayMix: 0.35,
      delayTime: 0.375,
      delayFeedback: 0.45
    }
  },

  // 4. THE CHAUFFEUR (4 Patches)
  {
    id: "duran-chauffeur-bass",
    name: "Chauffeur Dark Bass",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vco2Waveform: "sawtooth",
      vco1Range: 16,
      vco2Range: 16,
      vco2Detune: 0.15,
      vcoMix: 0.5,
      mixerVco1: 1.0,
      mixerVco2: 1.0,
      filterCutoff: 140,
      filterResonance: 0.45,
      filterEnvAmount: 0.8,
      env1Attack: 0.001,
      env1Decay: 0.2,
      env1Sustain: 0.0,
      env1Release: 0.15,
      env2Attack: 0.001,
      env2Decay: 0.25,
      env2Sustain: 0.85,
      env2Release: 0.2,
      distortionMix: 0.3,
      distortionAmount: 0.45,
      distortionMode: "tube"
    }
  },
  {
    id: "duran-chauffeur-pad",
    name: "Chauffeur Eerie Strings",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vco2Waveform: "pulse",
      vco2Detune: 0.2,
      vcoMix: 0.5,
      mixerVco1: 0.85,
      mixerVco2: 0.85,
      filterCutoff: 800,
      filterResonance: 0.12,
      env1Attack: 1.8,
      env1Decay: 2.5,
      env1Sustain: 0.9,
      env1Release: 3.0,
      env2Attack: 1.2,
      env2Decay: 2.2,
      env2Sustain: 0.95,
      env2Release: 3.0,
      chorusMix: 0.9,
      chorusMode: 3,
      reverbMix: 0.8,
      reverbTime: 6.0
    }
  },
  {
    id: "duran-chauffeur-lead",
    name: "Chauffeur Flute Solo",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sine",
      vco2Waveform: "triangle",
      vco1Range: 4,
      vco2Range: 4,
      vco2Detune: 0.05,
      vcoMix: 0.35,
      mixerVco1: 1.0,
      mixerVco2: 0.75,
      portamentoMode: "on",
      portamentoTime: 0.22,
      filterCutoff: 1600,
      filterResonance: 0.1,
      filterKeyboardTrack: 1.0,
      env2Attack: 0.08,
      env2Decay: 1.5,
      env2Sustain: 0.9,
      env2Release: 0.7,
      vcoLfoAmount: 0.05,
      lfoRate: 4.8,
      lfoDelay: 0.25,
      reverbMix: 0.65,
      reverbTime: 5.5,
      delayMix: 0.4,
      delayTime: 0.48,
      delayFeedback: 0.5
    }
  },
  {
    id: "duran-chauffeur-noise",
    name: "Chauffeur Industrial Hit",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "noise",
      vcoMix: 0.0,
      mixerVco1: 0.9,
      filterCutoff: 400,
      filterResonance: 0.85,
      filterEnvAmount: 0.75,
      env1Attack: 0.001,
      env1Decay: 0.15,
      env2Attack: 0.001,
      env2Decay: 0.18,
      env2Sustain: 0,
      reverbMix: 0.7,
      reverbTime: 4.5,
      delayMix: 0.3,
      delayTime: 0.33
    }
  },

  // 5. GIRLS ON FILM (4 Patches)
  {
    id: "duran-girls-bass",
    name: "Girls Slap Bass",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "square",
      vco2Waveform: "triangle",
      vco2Range: 16,
      vcoMix: 0.4,
      mixerVco1: 1.0,
      mixerVco2: 0.8,
      filterCutoff: 350,
      filterResonance: 0.5,
      filterEnvAmount: 0.7,
      env1Attack: 0.001,
      env1Decay: 0.12,
      env1Sustain: 0.0,
      env1Release: 0.1,
      env2Attack: 0.001,
      env2Decay: 0.2,
      env2Sustain: 0.8,
      env2Release: 0.15,
      chorusMix: 0.35,
      compMix: 0.85,
      compRatio: 6
    }
  },
  {
    id: "duran-girls-brass",
    name: "Girls Poly Brass",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vco2Waveform: "sawtooth",
      vco1Range: 8,
      vco2Range: 8,
      vco2Detune: 0.18,
      subOscEnabled: true,
      subOscMix: 0.15,
      vcoMix: 0.5,
      mixerVco1: 1.0,
      mixerVco2: 1.0,
      filterCutoff: 400,
      filterResonance: 0.2,
      filterEnvAmount: 0.80,
      env1Attack: 0.12,
      env1Decay: 0.8,
      env1Sustain: 0.35,
      env1Release: 0.45,
      env2Attack: 0.02,
      env2Decay: 1.0,
      env2Sustain: 0.82,
      env2Release: 0.45,
      chorusMix: 0.65,
      chorusMode: 2,
      reverbMix: 0.35,
      reverbTime: 3.2
    }
  },
  {
    id: "duran-girls-pad",
    name: "Girls Swirling Pad",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vco2Waveform: "sawtooth",
      vco1Range: 8,
      vco2Range: 8,
      vco2Detune: 0.24,
      vcoMix: 0.5,
      mixerVco1: 0.85,
      mixerVco2: 0.85,
      filterCutoff: 650,
      filterResonance: 0.28,
      filterEnvAmount: 0.45,
      filterLfoAmount: 0.45,
      lfoRate: 0.35,
      env1Attack: 1.0,
      env1Decay: 2.2,
      env1Sustain: 0.85,
      env1Release: 2.0,
      env2Attack: 0.7,
      env2Decay: 2.0,
      env2Sustain: 0.92,
      env2Release: 2.0,
      chorusMix: 0.9,
      chorusMode: 3,
      reverbMix: 0.6,
      reverbTime: 5.0,
      delayMix: 0.25,
      delayTime: 0.5
    }
  },
  {
    id: "duran-girls-shutter",
    name: "Girls Camera Shutter",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "noise",
      vcoMix: 0.0,
      mixerVco1: 1.0,
      filterCutoff: 4500,
      filterResonance: 0.35,
      filterEnvAmount: 0.3,
      lfoWaveform: "square",
      lfoRate: 13.5,
      vcaSource: "lfo",
      vcaLfoAmount: 1.0,
      env2Attack: 0.001,
      env2Decay: 2.0,
      env2Sustain: 1.0,
      env2Release: 0.1,
      reverbMix: 0.3,
      reverbTime: 1.5
    }
  },

  // 6. ORDINARY WORLD (4 Patches)
  {
    id: "duran-ordinary-bass",
    name: "Ordinary Warm Bass",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vco2Waveform: "sine",
      vco1Range: 16,
      vco2Range: 16,
      vcoMix: 0.35,
      mixerVco1: 0.9,
      mixerVco2: 0.9,
      filterCutoff: 140,
      filterResonance: 0.05,
      env1Attack: 0.01,
      env1Decay: 0.5,
      env2Attack: 0.005,
      env2Decay: 0.8,
      env2Sustain: 0.95,
      env2Release: 0.3,
      chorusMix: 0.2
    }
  },
  {
    id: "duran-ordinary-keys",
    name: "Ordinary Bell Keys",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sine",
      vco2Waveform: "triangle",
      vco2Range: 4,
      vco2Detune: 0.05,
      vcoMix: 0.25,
      mixerVco1: 1.0,
      mixerVco2: 1.0,
      filterCutoff: 2800,
      filterResonance: 0.05,
      env1Attack: 0.001,
      env1Decay: 0.7,
      env1Sustain: 0.0,
      env1Release: 0.8,
      env2Attack: 0.001,
      env2Decay: 1.6,
      env2Sustain: 0.1,
      env2Release: 1.0,
      chorusMix: 0.65,
      delayMix: 0.35,
      delayTime: 0.45,
      reverbMix: 0.5,
      tremoloMix: 0.25,
      tremoloRate: 4.5
    }
  },
  {
    id: "duran-ordinary-pad",
    name: "Ordinary Epic Pad",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vco2Waveform: "sawtooth",
      vco2Detune: 0.2,
      vcoMix: 0.5,
      mixerVco1: 0.85,
      mixerVco2: 0.85,
      filterCutoff: 1000,
      filterResonance: 0.1,
      env1Attack: 1.5,
      env1Decay: 2.2,
      env1Sustain: 0.85,
      env1Release: 2.2,
      env2Attack: 1.0,
      env2Decay: 2.0,
      env2Sustain: 0.95,
      env2Release: 2.2,
      chorusMix: 0.85,
      chorusMode: 3,
      reverbMix: 0.7,
      reverbTime: 5.0
    }
  },
  {
    id: "duran-ordinary-lead",
    name: "Ordinary Solo Lead",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vco2Waveform: "sawtooth",
      vco2Detune: 0.08,
      vcoMix: 0.4,
      mixerVco1: 1.0,
      mixerVco2: 0.9,
      portamentoMode: "on",
      portamentoTime: 0.12,
      filterCutoff: 2200,
      filterResonance: 0.2,
      env2Attack: 0.02,
      env2Decay: 1.2,
      env2Sustain: 0.85,
      env2Release: 0.4,
      vcoLfoAmount: 0.05,
      lfoRate: 5.0,
      delayMix: 0.4,
      delayTime: 0.375,
      reverbMix: 0.5
    }
  },

  // 7. A VIEW TO A KILL (4 Patches)
  {
    id: "duran-view-hit",
    name: "View Orchestra Hit",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vco2Waveform: "sawtooth",
      vco2Range: 4,
      vco2Detune: 0.22,
      vcoMix: 0.5,
      mixerVco1: 1.0,
      mixerVco2: 1.0,
      filterCutoff: 1800,
      filterResonance: 0.25,
      filterEnvAmount: 0.85,
      env1Attack: 0.001,
      env1Decay: 0.3,
      env1Sustain: 0.15,
      env1Release: 0.4,
      env2Attack: 0.001,
      env2Decay: 0.4,
      env2Sustain: 0.4,
      env2Release: 0.4,
      chorusMix: 0.7,
      distortionMix: 0.3,
      distortionAmount: 0.45,
      reverbMix: 0.6
    }
  },
  {
    id: "duran-view-bass",
    name: "View Driving Bass",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vco2Waveform: "square",
      vco1Range: 16,
      vco2Range: 16,
      vco2Detune: 0.12,
      vcoMix: 0.45,
      mixerVco1: 1.0,
      mixerVco2: 1.0,
      filterCutoff: 160,
      filterResonance: 0.2,
      filterEnvAmount: 0.65,
      env1Attack: 0.001,
      env1Decay: 0.2,
      env1Sustain: 0.1,
      env1Release: 0.12,
      env2Attack: 0.001,
      env2Decay: 0.26,
      env2Sustain: 0.8,
      env2Release: 0.15,
      chorusMix: 0.25,
      compMix: 0.8
    }
  },
  {
    id: "duran-view-strings",
    name: "View Drama Strings",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vco2Waveform: "sawtooth",
      vco1Range: 4,
      vco2Range: 8,
      vco2Detune: 0.24,
      vcoMix: 0.5,
      mixerVco1: 0.85,
      mixerVco2: 0.85,
      filterCutoff: 1800,
      filterResonance: 0.1,
      env1Attack: 0.25,
      env1Decay: 1.5,
      env1Sustain: 0.85,
      env1Release: 1.5,
      env2Attack: 0.18,
      env2Decay: 1.5,
      env2Sustain: 0.95,
      env2Release: 1.5,
      chorusMix: 0.9,
      chorusMode: 3,
      reverbMix: 0.6,
      reverbTime: 4.0
    }
  },
  {
    id: "duran-view-laser",
    name: "View Laser FX",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vcoMix: 1.0,
      mixerVco1: 1.0,
      filterCutoff: 7500,
      filterEnvAmount: -0.92,
      env1Attack: 0.005,
      env1Decay: 0.28,
      env1Sustain: 0,
      env2Attack: 0.005,
      env2Decay: 0.35,
      env2Sustain: 0,
      portamentoMode: "on",
      portamentoTime: 0.35,
      delayMix: 0.45,
      delayTime: 0.25
    }
  },

  // 8. THE WILD BOYS (4 Patches)
  {
    id: "duran-wild-bass",
    name: "Wild Dist Bass",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vco2Waveform: "square",
      vco1Range: 16,
      vco2Range: 16,
      vco2Detune: 0.16,
      vcoMix: 0.5,
      mixerVco1: 1.0,
      mixerVco2: 1.0,
      filterCutoff: 200,
      filterResonance: 0.3,
      filterEnvAmount: 0.75,
      env1Attack: 0.001,
      env1Decay: 0.24,
      env1Sustain: 0.05,
      env1Release: 0.15,
      env2Attack: 0.001,
      env2Decay: 0.32,
      env2Sustain: 0.85,
      env2Release: 0.2,
      distortionMix: 0.55,
      distortionAmount: 0.7,
      distortionMode: "feedback",
      distortionFeedbackAmount: 0.4
    }
  },
  {
    id: "duran-wild-hit",
    name: "Wild Metallic Hit",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vco2Waveform: "noise",
      vco2Range: 4,
      vcoMix: 0.4,
      mixerVco1: 1.0,
      mixerVco2: 0.8,
      crossMod: 0.65,
      filterCutoff: 1400,
      filterResonance: 0.4,
      filterEnvAmount: 0.8,
      env1Attack: 0.001,
      env1Decay: 0.18,
      env2Attack: 0.001,
      env2Decay: 0.22,
      env2Sustain: 0.0,
      distortionMix: 0.4,
      distortionAmount: 0.6,
      reverbMix: 0.7,
      reverbTime: 5.0
    }
  },
  {
    id: "duran-wild-pad",
    name: "Wild Gated Pad",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vco2Waveform: "sawtooth",
      vco2Detune: 0.2,
      vcoMix: 0.5,
      mixerVco1: 0.85,
      mixerVco2: 0.85,
      filterCutoff: 750,
      filterResonance: 0.15,
      env1Attack: 0.15,
      env1Decay: 0.8,
      env1Sustain: 0.8,
      env1Release: 1.0,
      env2Attack: 0.12,
      env2Decay: 0.9,
      env2Sustain: 0.85,
      env2Release: 1.0,
      chorusMix: 0.8,
      chorusMode: 2,
      tremoloMix: 0.6,
      tremoloRate: 6.5,
      tremoloDepth: 0.85
    }
  },
  {
    id: "duran-wild-drone",
    name: "Wild SciFi Drone",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "noise",
      vco2Waveform: "sawtooth",
      vco2Range: 8,
      vcoMix: 0.4,
      mixerVco1: 0.7,
      mixerVco2: 1.0,
      crossMod: 0.8,
      filterCutoff: 380,
      filterResonance: 0.65,
      filterLfoAmount: 0.7,
      lfoRate: 0.12,
      env1Attack: 2.0,
      env1Decay: 2.5,
      env1Sustain: 0.9,
      env1Release: 3.5,
      env2Attack: 1.8,
      env2Decay: 2.2,
      env2Sustain: 0.9,
      env2Release: 3.5,
      distortionMix: 0.4,
      distortionAmount: 0.5,
      reverbMix: 0.85,
      reverbTime: 8.0
    }
  },

  // 9. COME UNDONE (4 Patches)
  {
    id: "duran-undone-bass",
    name: "Undone Smooth Bass",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sine",
      vco2Waveform: "triangle",
      vco2Range: 16,
      vcoMix: 0.3,
      mixerVco1: 1.0,
      mixerVco2: 0.7,
      filterCutoff: 110,
      filterResonance: 0.05,
      env1Attack: 0.005,
      env1Decay: 0.4,
      env2Attack: 0.002,
      env2Decay: 0.6,
      env2Sustain: 0.95,
      env2Release: 0.25,
      chorusMix: 0.15,
      compMix: 0.8
    }
  },
  {
    id: "duran-undone-pad",
    name: "Undone Sweep Pad",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vco2Waveform: "sine",
      vco2Detune: 0.14,
      vcoMix: 0.4,
      mixerVco1: 0.8,
      mixerVco2: 0.8,
      filterCutoff: 300,
      filterResonance: 0.4,
      filterEnvAmount: 0.55,
      env1Attack: 1.2,
      env1Decay: 2.0,
      env1Sustain: 0.8,
      env1Release: 2.0,
      env2Attack: 0.8,
      env2Decay: 1.8,
      env2Sustain: 0.9,
      env2Release: 2.0,
      chorusMix: 0.85,
      reverbMix: 0.65,
      reverbTime: 4.5
    }
  },
  {
    id: "duran-undone-bell",
    name: "Undone Sparkle Bell",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sine",
      vco2Waveform: "sine",
      vco2Range: 2,
      vco2Detune: 0.06,
      vcoMix: 0.4,
      mixerVco1: 1.0,
      mixerVco2: 1.0,
      filterCutoff: 4000,
      filterResonance: 0.1,
      env1Attack: 0.001,
      env1Decay: 0.35,
      env1Sustain: 0,
      env1Release: 1.0,
      env2Attack: 0.001,
      env2Decay: 1.2,
      env2Sustain: 0,
      env2Release: 1.2,
      delayMix: 0.5,
      delayTime: 0.375,
      delayFeedback: 0.6,
      reverbMix: 0.6,
      reverbTime: 4.5
    }
  },
  {
    id: "duran-undone-keys",
    name: "Undone Electric Key",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "pulse",
      vco1PulseWidth: 0.18,
      vco2Waveform: "sine",
      vcoMix: 0.2,
      mixerVco1: 1.0,
      mixerVco2: 1.0,
      filterCutoff: 1600,
      filterResonance: 0.1,
      env1Attack: 0.002,
      env1Decay: 0.6,
      env1Sustain: 0.1,
      env1Release: 0.4,
      env2Attack: 0.002,
      env2Decay: 1.4,
      env2Sustain: 0.0,
      env2Release: 0.6,
      chorusMix: 0.7,
      tremoloMix: 0.4,
      tremoloRate: 5.2
    }
  },

  // 10. PLANET EARTH (4 Patches)
  {
    id: "duran-planet-bass",
    name: "Planet Drive Bass",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vco2Waveform: "square",
      vco1Range: 16,
      vco2Range: 16,
      vco2Detune: 0.1,
      vcoMix: 0.5,
      mixerVco1: 1.0,
      mixerVco2: 0.9,
      filterCutoff: 160,
      filterResonance: 0.2,
      filterEnvAmount: 0.7,
      env1Attack: 0.001,
      env1Decay: 0.22,
      env1Sustain: 0.15,
      env1Release: 0.15,
      env2Attack: 0.001,
      env2Decay: 0.3,
      env2Sustain: 0.8,
      env2Release: 0.18,
      chorusMix: 0.3,
      compMix: 0.75
    }
  },
  {
    id: "duran-planet-brass",
    name: "Planet Synth Brass",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vco2Waveform: "sawtooth",
      vco1Range: 8,
      vco2Range: 8,
      vco2Detune: 0.18,
      subOscEnabled: true,
      subOscMix: 0.15,
      vcoMix: 0.5,
      mixerVco1: 1.0,
      mixerVco2: 1.0,
      filterCutoff: 360,
      filterResonance: 0.22,
      filterEnvAmount: 0.84,
      env1Attack: 0.14,
      env1Decay: 0.85,
      env1Sustain: 0.32,
      env1Release: 0.5,
      env2Attack: 0.02,
      env2Decay: 1.1,
      env2Sustain: 0.85,
      env2Release: 0.5,
      chorusMix: 0.65,
      chorusMode: 2,
      reverbMix: 0.4,
      reverbTime: 3.5
    }
  },
  {
    id: "duran-planet-sweep",
    name: "Planet Reso Sweep",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vcoMix: 1.0,
      mixerVco1: 1.0,
      filterCutoff: 200,
      filterResonance: 0.82,
      filterEnvAmount: 0.9,
      env1Attack: 0.001,
      env1Decay: 0.35,
      env2Attack: 0.001,
      env2Decay: 0.4,
      env2Sustain: 0.0,
      delayMix: 0.4,
      delayTime: 0.33,
      delayFeedback: 0.4
    }
  },
  {
    id: "duran-planet-pad",
    name: "Planet Jupiter Pad",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vco2Waveform: "sawtooth",
      vco1Range: 8,
      vco2Range: 8,
      vco2Detune: 0.22,
      vcoMix: 0.5,
      mixerVco1: 0.85,
      mixerVco2: 0.85,
      filterCutoff: 800,
      filterResonance: 0.12,
      filterEnvAmount: 0.4,
      env1Attack: 0.6,
      env1Decay: 1.8,
      env1Sustain: 0.85,
      env1Release: 1.8,
      env2Attack: 0.4,
      env2Decay: 1.8,
      env2Sustain: 0.95,
      env2Release: 1.8,
      chorusMix: 0.85,
      chorusMode: 3,
      reverbMix: 0.55,
      reverbTime: 4.0
    }
  }
];

// DURAN DURAN CLASSIC MULTIS (Each with exactly 4 distinct patches/layers mapped beautifully)
export const DURAN_MULTIS: Multi[] = [
  {
    id: "multi-duran-rio",
    name: "Duran - Rio Multi",
    slots: [
      {
        patchId: "duran-rio-bass",
        lowNote: 0,
        highNote: 59,
        lowVelocity: 0,
        highVelocity: 127,
        lowMapVelocity: 0,
        highMapVelocity: 127,
        transposeOctave: 0,
        transposeNote: 0
      },
      {
        patchId: "duran-rio-arp",
        lowNote: 60,
        highNote: 127,
        lowVelocity: 0,
        highVelocity: 127,
        lowMapVelocity: 0,
        highMapVelocity: 127,
        transposeOctave: 0,
        transposeNote: 0
      },
      {
        patchId: "duran-rio-strings",
        lowNote: 60,
        highNote: 127,
        lowVelocity: 0,
        highVelocity: 95,
        lowMapVelocity: 0,
        highMapVelocity: 95,
        transposeOctave: 0,
        transposeNote: 0
      },
      {
        patchId: "duran-rio-brass",
        lowNote: 60,
        highNote: 127,
        lowVelocity: 96,
        highVelocity: 127,
        lowMapVelocity: 0,
        highMapVelocity: 127,
        transposeOctave: 0,
        transposeNote: 0
      }
    ]
  },
  {
    id: "multi-duran-wolf",
    name: "Duran - Hungry Wolf Multi",
    slots: [
      {
        patchId: "duran-wolf-bass",
        lowNote: 0,
        highNote: 59,
        lowVelocity: 0,
        highVelocity: 127,
        lowMapVelocity: 0,
        highMapVelocity: 127,
        transposeOctave: 0,
        transposeNote: 0
      },
      {
        patchId: "duran-wolf-arp",
        lowNote: 60,
        highNote: 127,
        lowVelocity: 0,
        highVelocity: 127,
        lowMapVelocity: 0,
        highMapVelocity: 127,
        transposeOctave: 0,
        transposeNote: 0
      },
      {
        patchId: "duran-wolf-pad",
        lowNote: 60,
        highNote: 127,
        lowVelocity: 0,
        highVelocity: 95,
        lowMapVelocity: 0,
        highMapVelocity: 95,
        transposeOctave: 0,
        transposeNote: 0
      },
      {
        patchId: "duran-wolf-lead",
        lowNote: 60,
        highNote: 127,
        lowVelocity: 96,
        highVelocity: 127,
        lowMapVelocity: 0,
        highMapVelocity: 127,
        transposeOctave: 0,
        transposeNote: 0
      }
    ]
  },
  {
    id: "multi-duran-prayer",
    name: "Duran - Save A Prayer Multi",
    slots: [
      {
        patchId: "duran-prayer-bass",
        lowNote: 0,
        highNote: 59,
        lowVelocity: 0,
        highVelocity: 127,
        lowMapVelocity: 0,
        highMapVelocity: 127,
        transposeOctave: 0,
        transposeNote: 0
      },
      {
        patchId: "duran-prayer-arp",
        lowNote: 60,
        highNote: 127,
        lowVelocity: 0,
        highVelocity: 127,
        lowMapVelocity: 0,
        highMapVelocity: 127,
        transposeOctave: 0,
        transposeNote: 0
      },
      {
        patchId: "duran-prayer-pad",
        lowNote: 60,
        highNote: 127,
        lowVelocity: 0,
        highVelocity: 127,
        lowMapVelocity: 0,
        highMapVelocity: 127,
        transposeOctave: 0,
        transposeNote: 0
      },
      {
        patchId: "duran-prayer-lead",
        lowNote: 72,
        highNote: 127,
        lowVelocity: 85,
        highVelocity: 127,
        lowMapVelocity: 0,
        highMapVelocity: 127,
        transposeOctave: 0,
        transposeNote: 0
      }
    ]
  },
  {
    id: "multi-duran-chauffeur",
    name: "Duran - Chauffeur Multi",
    slots: [
      {
        patchId: "duran-chauffeur-bass",
        lowNote: 0,
        highNote: 59,
        lowVelocity: 0,
        highVelocity: 127,
        lowMapVelocity: 0,
        highMapVelocity: 127,
        transposeOctave: 0,
        transposeNote: 0
      },
      {
        patchId: "duran-chauffeur-pad",
        lowNote: 60,
        highNote: 127,
        lowVelocity: 0,
        highVelocity: 127,
        lowMapVelocity: 0,
        highMapVelocity: 127,
        transposeOctave: 0,
        transposeNote: 0
      },
      {
        patchId: "duran-chauffeur-lead",
        lowNote: 60,
        highNote: 127,
        lowVelocity: 0,
        highVelocity: 127,
        lowMapVelocity: 0,
        highMapVelocity: 127,
        transposeOctave: 0,
        transposeNote: 0
      },
      {
        patchId: "duran-chauffeur-noise",
        lowNote: 0,
        highNote: 127,
        lowVelocity: 100,
        highVelocity: 127,
        lowMapVelocity: 0,
        highMapVelocity: 127,
        transposeOctave: 0,
        transposeNote: 0
      }
    ]
  },
  {
    id: "multi-duran-girls",
    name: "Duran - Girls On Film Multi",
    slots: [
      {
        patchId: "duran-girls-bass",
        lowNote: 0,
        highNote: 59,
        lowVelocity: 0,
        highVelocity: 127,
        lowMapVelocity: 0,
        highMapVelocity: 127,
        transposeOctave: 0,
        transposeNote: 0
      },
      {
        patchId: "duran-girls-brass",
        lowNote: 60,
        highNote: 127,
        lowVelocity: 96,
        highVelocity: 127,
        lowMapVelocity: 0,
        highMapVelocity: 127,
        transposeOctave: 0,
        transposeNote: 0
      },
      {
        patchId: "duran-girls-pad",
        lowNote: 60,
        highNote: 127,
        lowVelocity: 0,
        highVelocity: 95,
        lowMapVelocity: 0,
        highMapVelocity: 95,
        transposeOctave: 0,
        transposeNote: 0
      },
      {
        patchId: "duran-girls-shutter",
        lowNote: 84,
        highNote: 127,
        lowVelocity: 100,
        highVelocity: 127,
        lowMapVelocity: 0,
        highMapVelocity: 127,
        transposeOctave: 0,
        transposeNote: 0
      }
    ]
  },
  {
    id: "multi-duran-ordinary",
    name: "Duran - Ordinary World Multi",
    slots: [
      {
        patchId: "duran-ordinary-bass",
        lowNote: 0,
        highNote: 59,
        lowVelocity: 0,
        highVelocity: 127,
        lowMapVelocity: 0,
        highMapVelocity: 127,
        transposeOctave: 0,
        transposeNote: 0
      },
      {
        patchId: "duran-ordinary-keys",
        lowNote: 60,
        highNote: 127,
        lowVelocity: 0,
        highVelocity: 127,
        lowMapVelocity: 0,
        highMapVelocity: 127,
        transposeOctave: 0,
        transposeNote: 0
      },
      {
        patchId: "duran-ordinary-pad",
        lowNote: 60,
        highNote: 127,
        lowVelocity: 0,
        highVelocity: 127,
        lowMapVelocity: 0,
        highMapVelocity: 127,
        transposeOctave: 0,
        transposeNote: 0
      },
      {
        patchId: "duran-ordinary-lead",
        lowNote: 72,
        highNote: 127,
        lowVelocity: 96,
        highVelocity: 127,
        lowMapVelocity: 0,
        highMapVelocity: 127,
        transposeOctave: 0,
        transposeNote: 0
      }
    ]
  },
  {
    id: "multi-duran-view",
    name: "Duran - View To A Kill Multi",
    slots: [
      {
        patchId: "duran-view-hit",
        lowNote: 36,
        highNote: 59,
        lowVelocity: 100,
        highVelocity: 127,
        lowMapVelocity: 0,
        highMapVelocity: 127,
        transposeOctave: 0,
        transposeNote: 0
      },
      {
        patchId: "duran-view-bass",
        lowNote: 0,
        highNote: 59,
        lowVelocity: 0,
        highVelocity: 127,
        lowMapVelocity: 0,
        highMapVelocity: 127,
        transposeOctave: 0,
        transposeNote: 0
      },
      {
        patchId: "duran-view-strings",
        lowNote: 60,
        highNote: 127,
        lowVelocity: 0,
        highVelocity: 127,
        lowMapVelocity: 0,
        highMapVelocity: 127,
        transposeOctave: 0,
        transposeNote: 0
      },
      {
        patchId: "duran-view-laser",
        lowNote: 84,
        highNote: 127,
        lowVelocity: 96,
        highVelocity: 127,
        lowMapVelocity: 0,
        highMapVelocity: 127,
        transposeOctave: 0,
        transposeNote: 0
      }
    ]
  },
  {
    id: "multi-duran-wild",
    name: "Duran - Wild Boys Multi",
    slots: [
      {
        patchId: "duran-wild-bass",
        lowNote: 0,
        highNote: 59,
        lowVelocity: 0,
        highVelocity: 127,
        lowMapVelocity: 0,
        highMapVelocity: 127,
        transposeOctave: 0,
        transposeNote: 0
      },
      {
        patchId: "duran-wild-hit",
        lowNote: 60,
        highNote: 127,
        lowVelocity: 100,
        highVelocity: 127,
        lowMapVelocity: 0,
        highMapVelocity: 127,
        transposeOctave: 0,
        transposeNote: 0
      },
      {
        patchId: "duran-wild-pad",
        lowNote: 60,
        highNote: 127,
        lowVelocity: 0,
        highVelocity: 99,
        lowMapVelocity: 0,
        highMapVelocity: 99,
        transposeOctave: 0,
        transposeNote: 0
      },
      {
        patchId: "duran-wild-drone",
        lowNote: 0,
        highNote: 127,
        lowVelocity: 110,
        highVelocity: 127,
        lowMapVelocity: 0,
        highMapVelocity: 127,
        transposeOctave: 0,
        transposeNote: 0
      }
    ]
  },
  {
    id: "multi-duran-undone",
    name: "Duran - Come Undone Multi",
    slots: [
      {
        patchId: "duran-undone-bass",
        lowNote: 0,
        highNote: 59,
        lowVelocity: 0,
        highVelocity: 127,
        lowMapVelocity: 0,
        highMapVelocity: 127,
        transposeOctave: 0,
        transposeNote: 0
      },
      {
        patchId: "duran-undone-pad",
        lowNote: 60,
        highNote: 127,
        lowVelocity: 0,
        highVelocity: 127,
        lowMapVelocity: 0,
        highMapVelocity: 127,
        transposeOctave: 0,
        transposeNote: 0
      },
      {
        patchId: "duran-undone-bell",
        lowNote: 72,
        highNote: 127,
        lowVelocity: 0,
        highVelocity: 127,
        lowMapVelocity: 0,
        highMapVelocity: 127,
        transposeOctave: 0,
        transposeNote: 0
      },
      {
        patchId: "duran-undone-keys",
        lowNote: 60,
        highNote: 127,
        lowVelocity: 0,
        highVelocity: 127,
        lowMapVelocity: 0,
        highMapVelocity: 127,
        transposeOctave: 0,
        transposeNote: 0
      }
    ]
  },
  {
    id: "multi-duran-planet",
    name: "Duran - Planet Earth Multi",
    slots: [
      {
        patchId: "duran-planet-bass",
        lowNote: 0,
        highNote: 59,
        lowVelocity: 0,
        highVelocity: 127,
        lowMapVelocity: 0,
        highMapVelocity: 127,
        transposeOctave: 0,
        transposeNote: 0
      },
      {
        patchId: "duran-planet-brass",
        lowNote: 60,
        highNote: 127,
        lowVelocity: 96,
        highVelocity: 127,
        lowMapVelocity: 0,
        highMapVelocity: 127,
        transposeOctave: 0,
        transposeNote: 0
      },
      {
        patchId: "duran-planet-sweep",
        lowNote: 0,
        highNote: 127,
        lowVelocity: 105,
        highVelocity: 127,
        lowMapVelocity: 0,
        highMapVelocity: 127,
        transposeOctave: 0,
        transposeNote: 0
      },
      {
        patchId: "duran-planet-pad",
        lowNote: 60,
        highNote: 127,
        lowVelocity: 0,
        highVelocity: 95,
        lowMapVelocity: 0,
        highMapVelocity: 95,
        transposeOctave: 0,
        transposeNote: 0
      }
    ]
  }
];

// unified DURAN DURAN Setlist
export const DURAN_SETLIST: Setlist = {
  id: "setlist-duran-duran",
  name: "DURAN DURAN",
  songs: [
    { id: "song-duran-rio", name: "Rio", type: "multi", targetId: "multi-duran-rio" },
    { id: "song-duran-wolf", name: "Hungry Like the Wolf", type: "multi", targetId: "multi-duran-wolf" },
    { id: "song-duran-prayer", name: "Save a Prayer", type: "multi", targetId: "multi-duran-prayer" },
    { id: "song-duran-chauffeur", name: "The Chauffeur", type: "multi", targetId: "multi-duran-chauffeur" },
    { id: "song-duran-girls", name: "Girls on Film", type: "multi", targetId: "multi-duran-girls" },
    { id: "song-duran-ordinary", name: "Ordinary World", type: "multi", targetId: "multi-duran-ordinary" },
    { id: "song-duran-view", name: "A View to a Kill", type: "multi", targetId: "multi-duran-view" },
    { id: "song-duran-wild", name: "The Wild Boys", type: "multi", targetId: "multi-duran-wild" },
    { id: "song-duran-undone", name: "Come Undone", type: "multi", targetId: "multi-duran-undone" },
    { id: "song-duran-planet", name: "Planet Earth", type: "multi", targetId: "multi-duran-planet" }
  ]
};
