import { DEFAULT_PARAMS, Patch, Setlist } from "../types";

/**
 * LIVE SONG PRESET PATCHES
 * Authentic sound recreations for classic hits from Doe Maar, Het Goede Doel,
 * Frank Boeijen, U2, Talk Talk, Duran Duran, Springsteen, Depeche Mode,
 * The Cure, Madness, and more.
 */
export const LIVE_SONG_PATCHES: Patch[] = [
  // ==========================================
  // SET 1
  // ==========================================

  // 1. Doe Maar - Doris D.
  {
    id: "patch-doemaar-doris-d",
    name: "Doe Maar - Doris D. Organ/Bubble",
    group: "80s & Pop Hits",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "pulse",
      vco1Range: 8,
      vco1PulseWidth: 0.38,
      vco1PwmMode: "manual",
      vco2Waveform: "square",
      vco2Range: 8,
      vco2Detune: 0.08,
      vcoMix: 0.5,
      mixerVco1: 0.95,
      mixerVco2: 0.85,
      filterCutoff: 1800,
      filterResonance: 0.45,
      filterSlope: 24,
      filterEnvAmount: 0.65,
      filterVelocitySensitivity: 0.5,
      env1Attack: 0.002,
      env1Decay: 0.22,
      env1Sustain: 0.15,
      env1Release: 0.18,
      env2Attack: 0.001,
      env2Decay: 0.35,
      env2Sustain: 0.75,
      env2Release: 0.18,
      chorusMix: 0.45,
      chorusMode: 1,
      delayMix: 0.18,
      delayTime: 0.25,
      delayFeedback: 0.25,
      reverbMix: 0.22,
      reverbTime: 1.6,
      compMix: 0.65,
      compThreshold: -16
    }
  },

  // 2. Het Goede Doel - Nooduitgang
  {
    id: "patch-goededoel-nooduitgang",
    name: "Het Goede Doel - Nooduitgang Poly Brass",
    group: "80s & Pop Hits",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vco1Range: 8,
      vco2Waveform: "sawtooth",
      vco2Range: 8,
      vco2Detune: 0.24,
      vcoMix: 0.5,
      mixerVco1: 1.0,
      mixerVco2: 0.95,
      filterCutoff: 1600,
      filterResonance: 0.28,
      filterSlope: 24,
      filterEnvAmount: 0.62,
      filterVelocitySensitivity: 0.4,
      filterKeyboardTrack: 0.8,
      env1Attack: 0.02,
      env1Decay: 0.55,
      env1Sustain: 0.45,
      env1Release: 0.35,
      env2Attack: 0.015,
      env2Decay: 0.6,
      env2Sustain: 0.85,
      env2Release: 0.35,
      chorusMix: 0.65,
      chorusMode: 2,
      delayMix: 0.15,
      delayTime: 0.35,
      delayFeedback: 0.2,
      reverbMix: 0.3,
      reverbTime: 2.4,
      compMix: 0.75,
      compThreshold: -18,
      compRatio: 3.2
    }
  },

  // 3. Frank Boeijen Groep - Zwart wit (band)
  {
    id: "patch-frankboeijen-zwartwit",
    name: "Frank Boeijen - Zwart Wit Strings & Keys",
    group: "80s & Pop Hits",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vco1Range: 8,
      vco2Waveform: "pulse",
      vco2Range: 8,
      vco2PulseWidth: 0.45,
      vco2PwmMode: "lfo",
      vco2Detune: 0.16,
      vcoMix: 0.5,
      mixerVco1: 0.85,
      mixerVco2: 0.8,
      subOscEnabled: true,
      subOscWaveform: "triangle",
      subOscMix: 0.2,
      subOscOctave: -1,
      filterCutoff: 2100,
      filterResonance: 0.15,
      filterSlope: 24,
      filterEnvAmount: 0.35,
      filterKeyboardTrack: 0.9,
      lfoRate: 0.4,
      lfoWaveform: "sine",
      env1Attack: 0.18,
      env1Decay: 1.8,
      env1Sustain: 0.75,
      env1Release: 1.5,
      env2Attack: 0.12,
      env2Decay: 2.0,
      env2Sustain: 0.9,
      env2Release: 1.6,
      chorusMix: 0.7,
      chorusMode: 2,
      reverbMix: 0.42,
      reverbTime: 3.2,
      delayMix: 0.22,
      delayTime: 0.42,
      delayFeedback: 0.35
    }
  },

  // 4. U2 - The Unforgettable fire
  {
    id: "patch-u2-unforgettable-fire",
    name: "U2 - Unforgettable Fire Ambient Pad",
    group: "80s & Pop Hits",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vco1Range: 8,
      vco2Waveform: "pulse",
      vco2Range: 4,
      vco2PulseWidth: 0.48,
      vco2PwmMode: "lfo",
      vco2Detune: 0.22,
      vcoMix: 0.5,
      mixerVco1: 0.9,
      mixerVco2: 0.75,
      filterCutoff: 1750,
      filterResonance: 0.25,
      filterSlope: 24,
      filterEnvAmount: 0.3,
      filterKeyboardTrack: 0.95,
      lfoRate: 0.28,
      lfoWaveform: "sine",
      vcoLfoAmount: 0.012,
      filterLfoAmount: 0.15,
      env1Attack: 0.65,
      env1Decay: 2.8,
      env1Sustain: 0.85,
      env1Release: 2.5,
      env2Attack: 0.55,
      env2Decay: 3.0,
      env2Sustain: 0.95,
      env2Release: 2.6,
      chorusMix: 0.8,
      chorusMode: 3,
      delayMix: 0.45,
      delayTime: 0.44,
      delayFeedback: 0.52,
      reverbMix: 0.58,
      reverbTime: 5.5,
      reverbDamping: 0.4
    }
  },

  // 5. Talk Talk - Its my life
  {
    id: "patch-talktalk-its-my-life",
    name: "Talk Talk - It's My Life Jupiter Sweep",
    group: "80s & Pop Hits",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vco1Range: 8,
      vco2Waveform: "pulse",
      vco2Range: 8,
      vco2PulseWidth: 0.35,
      vco2Detune: 0.18,
      vcoMix: 0.5,
      mixerVco1: 1.0,
      mixerVco2: 0.9,
      filterCutoff: 1100,
      filterResonance: 0.68,
      filterSlope: 24,
      filterEnvAmount: 0.78,
      filterVelocitySensitivity: 0.55,
      filterKeyboardTrack: 0.85,
      env1Attack: 0.04,
      env1Decay: 0.48,
      env1Sustain: 0.35,
      env1Release: 0.4,
      env2Attack: 0.02,
      env2Decay: 0.65,
      env2Sustain: 0.85,
      env2Release: 0.45,
      chorusMix: 0.6,
      chorusMode: 2,
      delayMix: 0.28,
      delayTime: 0.375,
      delayFeedback: 0.4,
      reverbMix: 0.35,
      reverbTime: 2.8,
      compMix: 0.8,
      compThreshold: -16
    }
  },

  // 6. Duran Duran - Girls on film
  {
    id: "patch-duranduran-girls-on-film",
    name: "Duran Duran - Girls on Film Brass & Stabs",
    group: "80s & Pop Hits",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vco1Range: 8,
      vco2Waveform: "sawtooth",
      vco2Range: 8,
      vco2Detune: 0.18,
      vcoMix: 0.5,
      mixerVco1: 1.0,
      mixerVco2: 0.95,
      filterCutoff: 1400,
      filterResonance: 0.32,
      filterSlope: 24,
      filterEnvAmount: 0.68,
      filterVelocitySensitivity: 0.5,
      env1Attack: 0.005,
      env1Decay: 0.32,
      env1Sustain: 0.25,
      env1Release: 0.2,
      env2Attack: 0.003,
      env2Decay: 0.45,
      env2Sustain: 0.8,
      env2Release: 0.25,
      chorusMix: 0.55,
      chorusMode: 2,
      delayMix: 0.18,
      delayTime: 0.3,
      delayFeedback: 0.25,
      reverbMix: 0.25,
      reverbTime: 1.8,
      compMix: 0.85,
      compThreshold: -18,
      compRatio: 3.5
    }
  },

  // 7. Bruce Springsteen - Dancing in the dark
  {
    id: "patch-springsteen-dancing-in-dark",
    name: "Bruce Springsteen - Dancing In The Dark Poly",
    group: "80s & Pop Hits",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vco1Range: 8,
      vco2Waveform: "pulse",
      vco2Range: 8,
      vco2PulseWidth: 0.42,
      vco2PwmMode: "lfo",
      vco2Detune: 0.15,
      vcoMix: 0.5,
      mixerVco1: 1.0,
      mixerVco2: 0.95,
      filterCutoff: 2600,
      filterResonance: 0.22,
      filterSlope: 24,
      filterEnvAmount: 0.45,
      filterVelocitySensitivity: 0.45,
      filterKeyboardTrack: 0.9,
      lfoRate: 1.2,
      lfoWaveform: "sine",
      env1Attack: 0.008,
      env1Decay: 0.6,
      env1Sustain: 0.65,
      env1Release: 0.3,
      env2Attack: 0.005,
      env2Decay: 0.8,
      env2Sustain: 0.9,
      env2Release: 0.35,
      chorusMix: 0.68,
      chorusMode: 2,
      reverbMix: 0.32,
      reverbTime: 2.2,
      delayMix: 0.15,
      delayTime: 0.28,
      delayFeedback: 0.2,
      compMix: 0.8,
      compThreshold: -16
    }
  },

  // 8. The Romantics - Thats what I like about you
  {
    id: "patch-romantics-what-i-like",
    name: "The Romantics - What I Like Combo Organ",
    group: "80s & Pop Hits",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "square",
      vco1Range: 8,
      vco2Waveform: "pulse",
      vco2Range: 4,
      vco2PulseWidth: 0.3,
      vco2Detune: 0.06,
      vcoMix: 0.5,
      mixerVco1: 1.0,
      mixerVco2: 0.85,
      filterCutoff: 3800,
      filterResonance: 0.2,
      filterSlope: 12,
      filterEnvAmount: 0.2,
      filterKeyboardTrack: 1.0,
      env1Attack: 0.001,
      env1Decay: 0.1,
      env1Sustain: 0.95,
      env1Release: 0.08,
      env2Attack: 0.001,
      env2Decay: 0.1,
      env2Sustain: 1.0,
      env2Release: 0.08,
      chorusMix: 0.35,
      chorusMode: 1,
      distortionMix: 0.28,
      distortionAmount: 0.35,
      distortionMode: "tube",
      reverbMix: 0.2,
      reverbTime: 1.4,
      compMix: 0.7,
      compThreshold: -14
    }
  },

  // 9. Depeche Mode - I just cant get enough
  {
    id: "patch-depechemode-cant-get-enough",
    name: "Depeche Mode - Just Can't Get Enough Arp Lead",
    group: "80s & Pop Hits",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "pulse",
      vco1Range: 8,
      vco1PulseWidth: 0.45,
      vco2Waveform: "sawtooth",
      vco2Range: 8,
      vco2Detune: 0.12,
      vcoMix: 0.5,
      mixerVco1: 1.0,
      mixerVco2: 0.8,
      filterCutoff: 1650,
      filterResonance: 0.42,
      filterSlope: 24,
      filterEnvAmount: 0.65,
      filterVelocitySensitivity: 0.35,
      env1Attack: 0.002,
      env1Decay: 0.24,
      env1Sustain: 0.1,
      env1Release: 0.15,
      env2Attack: 0.001,
      env2Decay: 0.3,
      env2Sustain: 0.7,
      env2Release: 0.18,
      chorusMix: 0.5,
      chorusMode: 1,
      delayMix: 0.32,
      delayTime: 0.23, // ~130 bpm 16th delay
      delayFeedback: 0.38,
      reverbMix: 0.25,
      reverbTime: 1.5,
      compMix: 0.75,
      compThreshold: -16
    }
  },

  // 10. King - Love and pride
  {
    id: "patch-king-love-and-pride",
    name: "King - Love & Pride Synth Brass",
    group: "80s & Pop Hits",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vco1Range: 8,
      vco2Waveform: "sawtooth",
      vco2Range: 4,
      vco2Detune: 0.18,
      vcoMix: 0.5,
      mixerVco1: 1.0,
      mixerVco2: 0.88,
      filterCutoff: 2100,
      filterResonance: 0.35,
      filterSlope: 24,
      filterEnvAmount: 0.65,
      filterVelocitySensitivity: 0.45,
      filterKeyboardTrack: 0.85,
      env1Attack: 0.012,
      env1Decay: 0.45,
      env1Sustain: 0.4,
      env1Release: 0.25,
      env2Attack: 0.008,
      env2Decay: 0.55,
      env2Sustain: 0.85,
      env2Release: 0.28,
      chorusMix: 0.75,
      chorusMode: 2,
      delayMix: 0.2,
      delayTime: 0.32,
      delayFeedback: 0.28,
      reverbMix: 0.35,
      reverbTime: 2.4,
      compMix: 0.8,
      compThreshold: -18
    }
  },

  // 11. Dead or alive - You sin me round
  {
    id: "patch-deadoralive-spin-me-round",
    name: "Dead Or Alive - You Spin Me Round Lead",
    group: "80s & Pop Hits",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vco1Range: 8,
      vco2Waveform: "sawtooth",
      vco2Range: 8,
      vco2Detune: 0.28,
      vco2Sync: true,
      vcoMix: 0.5,
      mixerVco1: 1.0,
      mixerVco2: 1.0,
      filterCutoff: 2800,
      filterResonance: 0.4,
      filterSlope: 24,
      filterEnvAmount: 0.55,
      filterVelocitySensitivity: 0.4,
      env1Attack: 0.003,
      env1Decay: 0.35,
      env1Sustain: 0.5,
      env1Release: 0.2,
      env2Attack: 0.001,
      env2Decay: 0.45,
      env2Sustain: 0.9,
      env2Release: 0.22,
      chorusMix: 0.65,
      chorusMode: 2,
      delayMix: 0.26,
      delayTime: 0.23,
      delayFeedback: 0.35,
      reverbMix: 0.32,
      reverbTime: 2.0,
      compMix: 0.85,
      compThreshold: -20,
      compRatio: 3.5
    }
  },

  // 12. Doe Maar - Smoorverliefd
  {
    id: "patch-doemaar-smoorverliefd",
    name: "Doe Maar - Smoorverliefd Melodica & Organ",
    group: "80s & Pop Hits",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "pulse",
      vco1Range: 8,
      vco1PulseWidth: 0.32,
      vco2Waveform: "triangle",
      vco2Range: 8,
      vco2Detune: 0.08,
      vcoMix: 0.5,
      mixerVco1: 0.9,
      mixerVco2: 0.85,
      filterCutoff: 2200,
      filterResonance: 0.25,
      filterSlope: 24,
      filterEnvAmount: 0.4,
      filterVelocitySensitivity: 0.6,
      env1Attack: 0.015,
      env1Decay: 0.45,
      env1Sustain: 0.65,
      env1Release: 0.25,
      env2Attack: 0.01,
      env2Decay: 0.5,
      env2Sustain: 0.85,
      env2Release: 0.25,
      chorusMix: 0.4,
      chorusMode: 1,
      delayMix: 0.25,
      delayTime: 0.35,
      delayFeedback: 0.32,
      reverbMix: 0.28,
      reverbTime: 1.8,
      compMix: 0.7,
      compThreshold: -15
    }
  },

  // ==========================================
  // SET 2
  // ==========================================

  // 13. U2 - Where the streets have no name
  {
    id: "patch-u2-streets-no-name",
    name: "U2 - Streets Have No Name Eno Drone",
    group: "80s & Pop Hits",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vco1Range: 8,
      vco2Waveform: "triangle",
      vco2Range: 8,
      vco2Detune: 0.12,
      vcoMix: 0.5,
      mixerVco1: 0.85,
      mixerVco2: 0.95,
      subOscEnabled: true,
      subOscWaveform: "triangle",
      subOscMix: 0.25,
      subOscOctave: -1,
      filterCutoff: 1250,
      filterResonance: 0.15,
      filterSlope: 24,
      filterEnvAmount: 0.25,
      filterKeyboardTrack: 0.85,
      lfoRate: 0.22,
      lfoWaveform: "sine",
      filterLfoAmount: 0.12,
      vcoLfoAmount: 0.008,
      env1Attack: 0.85,
      env1Decay: 3.5,
      env1Sustain: 0.85,
      env1Release: 3.0,
      env2Attack: 0.75,
      env2Decay: 3.8,
      env2Sustain: 0.95,
      env2Release: 3.2,
      chorusMix: 0.75,
      chorusMode: 3,
      delayMix: 0.4,
      delayTime: 0.48,
      delayFeedback: 0.48,
      reverbMix: 0.65,
      reverbTime: 6.0,
      reverbDamping: 0.35
    }
  },

  // 14. Tears for Fears - Everybody wants to rule
  {
    id: "patch-tearsforfears-rule-the-world",
    name: "Tears For Fears - Rule The World Poly Keys",
    group: "80s & Pop Hits",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "pulse",
      vco1Range: 8,
      vco1PulseWidth: 0.46,
      vco1PwmMode: "lfo",
      vco2Waveform: "sawtooth",
      vco2Range: 8,
      vco2Detune: 0.16,
      vcoMix: 0.5,
      mixerVco1: 0.95,
      mixerVco2: 0.88,
      filterCutoff: 2400,
      filterResonance: 0.2,
      filterSlope: 24,
      filterEnvAmount: 0.42,
      filterVelocitySensitivity: 0.55,
      filterKeyboardTrack: 0.9,
      lfoRate: 0.8,
      lfoWaveform: "sine",
      env1Attack: 0.008,
      env1Decay: 0.85,
      env1Sustain: 0.55,
      env1Release: 0.45,
      env2Attack: 0.006,
      env2Decay: 1.1,
      env2Sustain: 0.85,
      env2Release: 0.5,
      chorusMix: 0.72,
      chorusMode: 2,
      delayMix: 0.3,
      delayTime: 0.38,
      delayFeedback: 0.35,
      reverbMix: 0.38,
      reverbTime: 2.6,
      compMix: 0.75,
      compThreshold: -16
    }
  },

  // 15. The Cure - A Forest
  {
    id: "patch-thecure-a-forest",
    name: "The Cure - A Forest Solina String Pad",
    group: "80s & Pop Hits",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vco1Range: 8,
      vco2Waveform: "sawtooth",
      vco2Range: 8,
      vco2Detune: 0.22,
      vcoMix: 0.5,
      mixerVco1: 1.0,
      mixerVco2: 0.92,
      subOscEnabled: true,
      subOscWaveform: "triangle",
      subOscMix: 0.18,
      subOscOctave: -1,
      filterCutoff: 1350,
      filterResonance: 0.35,
      filterSlope: 24,
      filterEnvAmount: 0.3,
      filterKeyboardTrack: 0.9,
      lfoRate: 0.45,
      lfoWaveform: "sine",
      filterLfoAmount: 0.15,
      env1Attack: 0.35,
      env1Decay: 2.2,
      env1Sustain: 0.75,
      env1Release: 2.0,
      env2Attack: 0.25,
      env2Decay: 2.5,
      env2Sustain: 0.9,
      env2Release: 2.2,
      chorusMix: 0.85,
      chorusMode: 3, // Solina Double-Triad Ensemble
      delayMix: 0.35,
      delayTime: 0.45,
      delayFeedback: 0.42,
      reverbMix: 0.52,
      reverbTime: 4.8,
      reverbDamping: 0.5
    }
  },

  // 16. JBB - SOLLICITERE 6 (buttons)
  {
    id: "patch-jbb-sollicitere",
    name: "Janse Bagge Bend - Sollicitere Brass Stabs",
    group: "80s & Pop Hits",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vco1Range: 8,
      vco2Waveform: "pulse",
      vco2Range: 4,
      vco2PulseWidth: 0.38,
      vco2Detune: 0.16,
      vcoMix: 0.5,
      mixerVco1: 1.0,
      mixerVco2: 0.95,
      filterCutoff: 2600,
      filterResonance: 0.32,
      filterSlope: 24,
      filterEnvAmount: 0.65,
      filterVelocitySensitivity: 0.5,
      filterKeyboardTrack: 0.8,
      env1Attack: 0.005,
      env1Decay: 0.32,
      env1Sustain: 0.35,
      env1Release: 0.18,
      env2Attack: 0.003,
      env2Decay: 0.45,
      env2Sustain: 0.8,
      env2Release: 0.2,
      chorusMix: 0.5,
      chorusMode: 2,
      delayMix: 0.15,
      delayTime: 0.26,
      delayFeedback: 0.2,
      reverbMix: 0.28,
      reverbTime: 1.8,
      compMix: 0.85,
      compThreshold: -18,
      compRatio: 3.5
    }
  },

  // 17. Doe Maar - Belle Helene
  {
    id: "patch-doemaar-belle-helene",
    name: "Doe Maar - Belle Hélène Whistle & Skank",
    group: "80s & Pop Hits",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sine",
      vco1Range: 4,
      vco2Waveform: "pulse",
      vco2Range: 8,
      vco2PulseWidth: 0.35,
      vco2Detune: 0.08,
      vcoMix: 0.5,
      mixerVco1: 0.95,
      mixerVco2: 0.85,
      filterCutoff: 3200,
      filterResonance: 0.35,
      filterSlope: 24,
      filterEnvAmount: 0.45,
      filterVelocitySensitivity: 0.55,
      env1Attack: 0.02,
      env1Decay: 0.35,
      env1Sustain: 0.6,
      env1Release: 0.2,
      env2Attack: 0.015,
      env2Decay: 0.45,
      env2Sustain: 0.85,
      env2Release: 0.22,
      chorusMix: 0.42,
      chorusMode: 1,
      delayMix: 0.28,
      delayTime: 0.32,
      delayFeedback: 0.35,
      reverbMix: 0.3,
      reverbTime: 2.0,
      compMix: 0.7,
      compThreshold: -16
    }
  },

  // 18. Doe Maar - De Bom
  {
    id: "patch-doemaar-de-bom",
    name: "Doe Maar - De Bom Clock Chimes & EP",
    group: "80s & Pop Hits",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sine",
      vco1Range: 4,
      vco2Waveform: "pulse",
      vco2Range: 8,
      vco2PulseWidth: 0.4,
      vco2Detune: 0.12,
      vcoMix: 0.5,
      mixerVco1: 1.0,
      mixerVco2: 0.75,
      filterCutoff: 2800,
      filterResonance: 0.22,
      filterSlope: 24,
      filterEnvAmount: 0.48,
      filterVelocitySensitivity: 0.65,
      env1Attack: 0.001,
      env1Decay: 0.95,
      env1Sustain: 0.25,
      env1Release: 0.65,
      env2Attack: 0.001,
      env2Decay: 1.2,
      env2Sustain: 0.7,
      env2Release: 0.75,
      chorusMix: 0.6,
      chorusMode: 2,
      delayMix: 0.35,
      delayTime: 0.375,
      delayFeedback: 0.4,
      reverbMix: 0.45,
      reverbTime: 3.0,
      compMix: 0.75,
      compThreshold: -15
    }
  },

  // 19. Madness - Baggy Trousers
  {
    id: "patch-madness-baggy-trousers",
    name: "Madness - Baggy Trousers Ska Organ & Piano",
    group: "80s & Pop Hits",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "square",
      vco1Range: 8,
      vco2Waveform: "pulse",
      vco2Range: 8,
      vco2PulseWidth: 0.25,
      vco2Detune: 0.08,
      vcoMix: 0.5,
      mixerVco1: 1.0,
      mixerVco2: 0.9,
      filterCutoff: 3600,
      filterResonance: 0.25,
      filterSlope: 12,
      filterEnvAmount: 0.35,
      filterVelocitySensitivity: 0.5,
      env1Attack: 0.001,
      env1Decay: 0.15,
      env1Sustain: 0.8,
      env1Release: 0.1,
      env2Attack: 0.001,
      env2Decay: 0.2,
      env2Sustain: 0.95,
      env2Release: 0.1,
      chorusMix: 0.35,
      chorusMode: 1,
      distortionMix: 0.2,
      distortionAmount: 0.25,
      distortionMode: "tube",
      reverbMix: 0.22,
      reverbTime: 1.4,
      compMix: 0.8,
      compThreshold: -18
    }
  },

  // 20. Madness - One step Beyond POLONAISE
  {
    id: "patch-madness-one-step-beyond",
    name: "Madness - One Step Beyond Stomp Organ",
    group: "80s & Pop Hits",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "square",
      vco1Range: 8,
      vco2Waveform: "square",
      vco2Range: 4,
      vco2Detune: 0.06,
      vcoMix: 0.5,
      mixerVco1: 1.0,
      mixerVco2: 0.95,
      filterCutoff: 4200,
      filterResonance: 0.18,
      filterSlope: 12,
      filterEnvAmount: 0.2,
      env1Attack: 0.001,
      env1Decay: 0.12,
      env1Sustain: 0.95,
      env1Release: 0.08,
      env2Attack: 0.001,
      env2Decay: 0.15,
      env2Sustain: 1.0,
      env2Release: 0.08,
      chorusMix: 0.3,
      chorusMode: 1,
      distortionMix: 0.25,
      distortionAmount: 0.3,
      distortionMode: "tube",
      reverbMix: 0.25,
      reverbTime: 1.6,
      compMix: 0.85,
      compThreshold: -18
    }
  },

  // 21. Proclaimers - 500 Miles
  {
    id: "patch-proclaimers-500-miles",
    name: "The Proclaimers - 500 Miles Piano & Accordion",
    group: "80s & Pop Hits",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "pulse",
      vco1Range: 8,
      vco1PulseWidth: 0.42,
      vco2Waveform: "square",
      vco2Range: 8,
      vco2Detune: 0.14,
      vcoMix: 0.5,
      mixerVco1: 1.0,
      mixerVco2: 0.85,
      filterCutoff: 2900,
      filterResonance: 0.2,
      filterSlope: 24,
      filterEnvAmount: 0.45,
      filterVelocitySensitivity: 0.6,
      env1Attack: 0.003,
      env1Decay: 0.65,
      env1Sustain: 0.65,
      env1Release: 0.3,
      env2Attack: 0.002,
      env2Decay: 0.8,
      env2Sustain: 0.9,
      env2Release: 0.35,
      chorusMix: 0.55,
      chorusMode: 1,
      reverbMix: 0.3,
      reverbTime: 2.0,
      compMix: 0.75,
      compThreshold: -16
    }
  },

  // 22. Peter Schilling - Major Tom
  {
    id: "patch-peterschilling-major-tom",
    name: "Peter Schilling - Major Tom NDW Lead & Arp",
    group: "80s & Pop Hits",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vco1Range: 8,
      vco2Waveform: "pulse",
      vco2Range: 8,
      vco2PulseWidth: 0.36,
      vco2Detune: 0.22,
      vcoMix: 0.5,
      mixerVco1: 1.0,
      mixerVco2: 0.95,
      filterCutoff: 2100,
      filterResonance: 0.48,
      filterSlope: 24,
      filterEnvAmount: 0.65,
      filterVelocitySensitivity: 0.45,
      env1Attack: 0.005,
      env1Decay: 0.38,
      env1Sustain: 0.35,
      env1Release: 0.28,
      env2Attack: 0.002,
      env2Decay: 0.5,
      env2Sustain: 0.85,
      env2Release: 0.3,
      chorusMix: 0.68,
      chorusMode: 2,
      delayMix: 0.35,
      delayTime: 0.375,
      delayFeedback: 0.42,
      reverbMix: 0.4,
      reverbTime: 3.2,
      compMix: 0.8,
      compThreshold: -18
    }
  },

  // ==========================================
  // EXTRA / ENCORE
  // ==========================================

  // 23. Spider Murphy Gang - Skandal im Sperrbezirk
  {
    id: "patch-spidermurphy-skandal",
    name: "Spider Murphy Gang - Skandal Boogie & Brass",
    group: "80s & Pop Hits",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vco1Range: 8,
      vco2Waveform: "pulse",
      vco2Range: 8,
      vco2PulseWidth: 0.4,
      vco2Detune: 0.2,
      vcoMix: 0.5,
      mixerVco1: 1.0,
      mixerVco2: 0.95,
      filterCutoff: 2700,
      filterResonance: 0.35,
      filterSlope: 24,
      filterEnvAmount: 0.68,
      filterVelocitySensitivity: 0.5,
      env1Attack: 0.004,
      env1Decay: 0.35,
      env1Sustain: 0.4,
      env1Release: 0.2,
      env2Attack: 0.002,
      env2Decay: 0.5,
      env2Sustain: 0.85,
      env2Release: 0.22,
      chorusMix: 0.65,
      chorusMode: 2,
      reverbMix: 0.28,
      reverbTime: 1.8,
      delayMix: 0.18,
      delayTime: 0.25,
      delayFeedback: 0.22,
      compMix: 0.85,
      compThreshold: -18,
      compRatio: 3.5
    }
  },

  // 24. Het Goede Doel - België
  {
    id: "patch-goededoel-belgie",
    name: "Het Goede Doel - België Ostinato & Brass",
    group: "80s & Pop Hits",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vco1Range: 8,
      vco2Waveform: "pulse",
      vco2Range: 8,
      vco2PulseWidth: 0.44,
      vco2Detune: 0.18,
      vcoMix: 0.5,
      mixerVco1: 1.0,
      mixerVco2: 0.92,
      filterCutoff: 2200,
      filterResonance: 0.38,
      filterSlope: 24,
      filterEnvAmount: 0.65,
      filterVelocitySensitivity: 0.45,
      env1Attack: 0.006,
      env1Decay: 0.45,
      env1Sustain: 0.4,
      env1Release: 0.25,
      env2Attack: 0.003,
      env2Decay: 0.6,
      env2Sustain: 0.85,
      env2Release: 0.28,
      chorusMix: 0.7,
      chorusMode: 2,
      delayMix: 0.28,
      delayTime: 0.32,
      delayFeedback: 0.35,
      reverbMix: 0.35,
      reverbTime: 2.5,
      compMix: 0.8,
      compThreshold: -18
    }
  }
];

// Pre-assembled Setlists for Live Performance View & MIDI PC
export const SETLIST_SET_1: Setlist = {
  id: "setlist-live-set-1",
  name: "SET 1 (Nederpop & Pop Classics)",
  songs: [
    { id: "song-doris-d", name: "Doe Maar - Doris D.", type: "patch", targetId: "patch-doemaar-doris-d", programChange: 0 },
    { id: "song-nooduitgang", name: "Het Goede Doel - Nooduitgang", type: "patch", targetId: "patch-goededoel-nooduitgang", programChange: 1 },
    { id: "song-zwartwit", name: "Frank Boeijen - Zwart wit", type: "patch", targetId: "patch-frankboeijen-zwartwit", programChange: 2 },
    { id: "song-unforgettable-fire", name: "U2 - The Unforgettable Fire", type: "patch", targetId: "patch-u2-unforgettable-fire", programChange: 3 },
    { id: "song-its-my-life", name: "Talk Talk - Its my life", type: "patch", targetId: "patch-talktalk-its-my-life", programChange: 4 },
    { id: "song-girls-on-film", name: "Duran Duran - Girls on film", type: "patch", targetId: "patch-duranduran-girls-on-film", programChange: 5 },
    { id: "song-dancing-in-dark", name: "Bruce Springsteen - Dancing in the dark", type: "patch", targetId: "patch-springsteen-dancing-in-dark", programChange: 6 },
    { id: "song-what-i-like", name: "The Romantics - Thats what I like about you", type: "patch", targetId: "patch-romantics-what-i-like", programChange: 7 },
    { id: "song-cant-get-enough", name: "Depeche Mode - I just cant get enough", type: "patch", targetId: "patch-depechemode-cant-get-enough", programChange: 8 },
    { id: "song-love-and-pride", name: "King - Love and pride", type: "patch", targetId: "patch-king-love-and-pride", programChange: 9 },
    { id: "song-spin-me-round", name: "Dead or Alive - You spin me round", type: "patch", targetId: "patch-deadoralive-spin-me-round", programChange: 10 },
    { id: "song-smoorverliefd", name: "Doe Maar - Smoorverliefd", type: "patch", targetId: "patch-doemaar-smoorverliefd", programChange: 11 }
  ]
};

export const SETLIST_SET_2: Setlist = {
  id: "setlist-live-set-2",
  name: "SET 2 (80s Anthems & Ska)",
  songs: [
    { id: "song-streets-no-name", name: "U2 - Where the streets have no name", type: "patch", targetId: "patch-u2-streets-no-name", programChange: 0 },
    { id: "song-rule-the-world", name: "Tears for Fears - Everybody wants to rule", type: "patch", targetId: "patch-tearsforfears-rule-the-world", programChange: 1 },
    { id: "song-a-forest", name: "The Cure - A Forest", type: "patch", targetId: "patch-thecure-a-forest", programChange: 2 },
    { id: "song-sollicitere", name: "JBB - SOLLICITERE 6", type: "patch", targetId: "patch-jbb-sollicitere", programChange: 3 },
    { id: "song-belle-helene", name: "Doe Maar - Belle Helene", type: "patch", targetId: "patch-doemaar-belle-helene", programChange: 4 },
    { id: "song-de-bom", name: "Doe Maar - De Bom", type: "patch", targetId: "patch-doemaar-de-bom", programChange: 5 },
    { id: "song-baggy-trousers", name: "Madness - Baggy Trousers", type: "patch", targetId: "patch-madness-baggy-trousers", programChange: 6 },
    { id: "song-one-step-beyond", name: "Madness - One step Beyond POLONAISE", type: "patch", targetId: "patch-madness-one-step-beyond", programChange: 7 },
    { id: "song-500-miles", name: "Proclaimers - 500 Miles", type: "patch", targetId: "patch-proclaimers-500-miles", programChange: 8 },
    { id: "song-major-tom", name: "Peter Schilling - Major Tom", type: "patch", targetId: "patch-peterschilling-major-tom", programChange: 9 },
    { id: "song-skandal", name: "Spider Murphy Gang - Skandal ...", type: "patch", targetId: "patch-spidermurphy-skandal", programChange: 10 },
    { id: "song-belgie", name: "Het Goede Doel - België", type: "patch", targetId: "patch-goededoel-belgie", programChange: 11 }
  ]
};
