/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { DEFAULT_PARAMS, Patch } from "../types";

export const PRESET_PATCHES: Patch[] = [
  // BASSES
  {
    id: "bass-1",
    name: "Classic 80s Bass",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vco2Waveform: "square",
      vco2Range: 16,
      vcoMix: 0.6,
      mixerVco1: 0.9,
      mixerVco2: 0.7,
      filterCutoff: 150,
      filterResonance: 0.25,
      filterEnvAmount: 0.65,
      env1Attack: 0.002,
      env1Decay: 0.35,
      env1Sustain: 0.1,
      env1Release: 0.2,
      env2Attack: 0.002,
      env2Decay: 0.2,
      env2Sustain: 1.0,
      chorusMix: 0.4,
      filterKeyboardTrack: 0.3,
      reverbMix: 0.1,
    }
  },
  {
    id: "bass-2",
    name: "Dark Acid Bass",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vcoMix: 1.0,
      mixerVco1: 1.0,
      filterCutoff: 450,
      filterResonance: 0.85,
      filterEnvAmount: 0.9,
      env1Attack: 0.005,
      env1Decay: 0.25,
      env1Sustain: 0,
      env2Attack: 0.005,
      env2Decay: 0.4,
      env2Sustain: 0.6,
      distortionMix: 0.45,
      distortionAmount: 0.7,
    }
  },
  {
    id: "bass-3",
    name: "Moog-ish Punch",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "square",
      vco2Waveform: "sawtooth",
      vco2Freq: 0.02,
      vco2Detune: 0.1,
      vcoMix: 0.5,
      mixerVco1: 0.8,
      mixerVco2: 0.8,
      filterCutoff: 180,
      filterResonance: 0.45,
      filterEnvAmount: 0.75,
      env1Attack: 0.001,
      env1Decay: 0.4,
      env1Sustain: 0.2,
      env1Release: 0.4,
      env2Attack: 0.001,
      env2Decay: 0.6,
      env2Sustain: 0.8,
    }
  },
  {
    id: "bass-4",
    name: "Slap Poly Bass",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "pulse",
      vco1PulseWidth: 0.35,
      vcoMix: 1.0,
      mixerVco1: 1.0,
      filterCutoff: 1200,
      filterResonance: 0.15,
      filterEnvAmount: 0.45,
      env1Attack: 0.005,
      env1Decay: 0.15,
      env1Sustain: 0,
      env2Attack: 0.005,
      env2Decay: 0.2,
      env2Sustain: 0.8,
      chorusMix: 0.4,
    }
  },

  // LEADS
  {
    id: "lead-1",
    name: "Blade Runner",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vco2Waveform: "sawtooth",
      vco2Detune: 0.15,
      vcoMix: 0.5,
      mixerVco1: 0.7,
      mixerVco2: 0.7,
      filterCutoff: 800,
      filterResonance: 0.1,
      vcaEnvAmount: 1.0,
      env2Attack: 0.8,
      env2Decay: 2.0,
      env2Sustain: 0.7,
      env2Release: 3.5,
      vcoLfoAmount: 0.02,
      lfoRate: 4.5,
      chorusMix: 0.8,
      reverbMix: 0.85,
      reverbTime: 6.0,
      delayMix: 0.35,
      delayTime: 0.4,
    }
  },
  {
    id: "lead-2",
    name: "Sync Lead 80s",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vco2Waveform: "sawtooth",
      vco2Sync: true,
      vco2Freq: 4.0,
      vcoMix: 0.4,
      mixerVco1: 0.6,
      mixerVco2: 0.9,
      filterCutoff: 3500,
      filterEnvAmount: 0.85,
      env1Attack: 0.05,
      env1Decay: 0.6,
      env1Sustain: 0.2,
      env2Attack: 0.01,
      env2Sustain: 0.9,
      distortionMix: 0.25,
      chorusMix: 0.3,
    }
  },
  {
    id: "lead-3",
    name: "Funk Tri-Lead",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "triangle",
      vco2Waveform: "sine",
      vco2Detune: 0.05,
      vcoMix: 0.6,
      portamentoMode: "on",
      portamentoTime: 0.18,
      filterCutoff: 1800,
      filterKeyboardTrack: 1.0,
      env2Attack: 0.01,
      lfoRate: 6.0,
      vcaLfoAmount: 0.15,
      vcoLfoAmount: 0.05,
    }
  },
  {
    id: "lead-4",
    name: "Screaming Solo",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vco2Waveform: "square",
      vco2Detune: 0.2,
      vcoMix: 0.5,
      mixerVco1: 0.8,
      mixerVco2: 0.8,
      filterCutoff: 4500,
      filterResonance: 0.55,
      distortionMix: 0.65,
      distortionAmount: 0.85,
      delayMix: 0.45,
      delayTime: 0.35,
      reverbMix: 0.3,
    }
  },

  // PADS
  {
    id: "pad-1",
    name: "Dreamy Clouds",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sine",
      vco2Waveform: "sine",
      vco2Detune: 0.12,
      vcoMix: 0.5,
      filterCutoff: 650,
      filterLfoAmount: 0.35,
      lfoRate: 0.3,
      env2Attack: 2.5,
      env2Sustain: 0.9,
      env2Release: 5.0,
      chorusMix: 0.85,
      reverbMix: 0.9,
      reverbTime: 6.0,
      delayMix: 0.4,
      delayTime: 0.6,
      delayFeedback: 0.5,
    }
  },
  {
    id: "pad-2",
    name: "Jupiter Strings",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vco2Waveform: "sawtooth",
      vco2Detune: 0.08,
      vcoMix: 0.5,
      mixerVco1: 0.7,
      mixerVco2: 0.7,
      filterCutoff: 1100,
      filterKeyboardTrack: 1.0,
      filterSlope: 24,
      env2Attack: 0.6,
      env2Sustain: 0.8,
      env2Release: 2.5,
      chorusMix: 0.75,
      reverbMix: 0.4,
      lfoRate: 0.45,
      filterLfoAmount: 0.25,
      vcoLfoAmount: 0.01,
    }
  },
  {
    id: "pad-3",
    name: "Vangelis Brass",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vco2Waveform: "sawtooth",
      vco2Detune: 0.14,
      vcoMix: 0.5,
      mixerVco1: 0.8,
      mixerVco2: 0.8,
      filterCutoff: 800,
      filterEnvAmount: 0.6,
      filterKeyboardTrack: 0.8,
      env1Attack: 0.6,
      env1Decay: 2.5,
      env1Sustain: 0.4,
      env2Attack: 0.5,
      env2Sustain: 0.7,
      env2Release: 3.0,
      chorusMix: 0.65,
      reverbMix: 0.75,
      reverbTime: 4.5,
    }
  },
  {
    id: "pad-4",
    name: "Dark Space",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "noise",
      vco2Waveform: "sine",
      vcoMix: 0.85,
      filterCutoff: 350,
      filterResonance: 0.7,
      env2Attack: 4.0,
      env2Release: 6.0,
      reverbMix: 0.95,
      reverbTime: 8.0,
      tremoloMix: 0.35,
      tremoloRate: 0.2,
    }
  },

  // KEYS
  {
    id: "keys-1",
    name: "Classic DX E-Piano",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sine",
      vco2Waveform: "sine",
      vco2Range: 4,
      vco2Detune: 0.03,
      vcoMix: 0.4,
      mixerVco1: 0.7,
      mixerVco2: 0.4,
      filterCutoff: 3000,
      filterKeyboardTrack: 1.0,
      env1Attack: 0.001,
      env1Decay: 1.2,
      env1Sustain: 0,
      env2Attack: 0.001,
      env2Decay: 4.0,
      env2Sustain: 0,
      chorusMix: 0.6,
      delayMix: 0.3,
      tremoloMix: 0.25,
      tremoloRate: 4.5,
    }
  },
  {
    id: "keys-2",
    name: "Wurlitzerish",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "pulse",
      vco1PulseWidth: 0.15,
      vcoMix: 1.0,
      mixerVco1: 1.0,
      filterCutoff: 2800,
      filterResonance: 0.25,
      env2Attack: 0.015,
      env2Decay: 2.0,
      env2Sustain: 0.05,
      distortionMix: 0.2,
      distortionAmount: 0.3,
      tremoloMix: 0.45,
      tremoloRate: 6.5,
    }
  },
  {
    id: "keys-3",
    name: "Pluck Bell",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sine",
      vco2Waveform: "triangle",
      vco2Range: 2,
      vco2Freq: 0.01,
      vcoMix: 0.35,
      mixerVco1: 0.5,
      mixerVco2: 0.8,
      filterCutoff: 5000,
      env2Attack: 0.001,
      env2Decay: 1.0,
      env2Sustain: 0,
      delayMix: 0.4,
      delayTime: 0.3,
      delayFeedback: 0.5,
    }
  },
  {
    id: "keys-4",
    name: "Retro Poly",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vco2Waveform: "square",
      vco2Detune: 0.06,
      vcoMix: 0.5,
      mixerVco1: 0.8,
      mixerVco2: 0.7,
      filterCutoff: 1800,
      filterEnvAmount: 0.5,
      env1Attack: 0.04,
      env1Decay: 0.8,
      env1Sustain: 0.1,
      env2Attack: 0.04,
      env2Sustain: 0.8,
      chorusMix: 0.4,
      reverbMix: 0.2,
    }
  },

  // STRINGS/BRASS
  {
    id: "brass-1",
    name: "Mega Brass 80s",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vco2Waveform: "sawtooth",
      vco2Freq: 0.01,
      vco2Detune: 0.18,
      vcoMix: 0.5,
      mixerVco1: 0.9,
      mixerVco2: 0.9,
      filterCutoff: 900,
      filterEnvAmount: 0.75,
      env1Attack: 0.08,
      env1Decay: 0.6,
      env1Sustain: 0.3,
      env2Attack: 0.08,
      env2Sustain: 0.9,
      env2Release: 0.8,
      chorusMix: 0.45,
      reverbMix: 0.6,
      reverbTime: 3.0,
    }
  },
  {
    id: "brass-2",
    name: "Synth Horns",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vco2Waveform: "sawtooth",
      vco2Detune: 0.1,
      vcoMix: 0.5,
      mixerVco1: 0.8,
      mixerVco2: 0.7,
      filterCutoff: 1400,
      filterResonance: 0.15,
      filterEnvAmount: 0.4,
      env1Attack: 0.02,
      env1Decay: 0.4,
      env2Attack: 0.02,
      env2Decay: 0.5,
      env2Sustain: 0.8,
      chorusMix: 0.25,
    }
  },
  {
    id: "strings-1",
    name: "Solina Strings",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vcoMix: 1.0,
      mixerVco1: 1.0,
      filterCutoff: 3000,
      filterKeyboardTrack: 1.0,
      env2Attack: 0.45,
      env2Sustain: 0.9,
      env2Release: 1.8,
      chorusMix: 0.95,
      chorusMode: 2,
      leslieMix: 0.45,
      leslieRate: 0.6,
    }
  },
  {
    id: "strings-2",
    name: "80s Orchestral",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vco2Waveform: "pulse",
      vco2Detune: 0.15,
      vcoMix: 0.5,
      mixerVco1: 0.7,
      mixerVco2: 0.8,
      filterCutoff: 2800,
      filterKeyboardTrack: 0.9,
      env2Attack: 0.25,
      env2Sustain: 0.9,
      env2Release: 1.5,
      chorusMix: 0.65,
      reverbMix: 0.55,
      reverbTime: 3.0,
    }
  },

  // FX/EXP
  {
    id: "fx-1",
    name: "Windy Night",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "noise",
      vcoMix: 1.0,
      mixerVco1: 1.0,
      filterCutoff: 150,
      filterResonance: 0.85,
      filterLfoAmount: 0.8,
      lfoRate: 0.12,
      env2Attack: 3.0,
      env2Sustain: 1.0,
      env2Release: 4.0,
      reverbMix: 0.8,
      reverbTime: 10.0,
    }
  },
  {
    id: "fx-2",
    name: "Retro Computer",
    params: {
      ...DEFAULT_PARAMS,
      arpEnabled: true,
      arpMode: "random",
      arpRate: 350,
      arpRange: 3,
      vco1Waveform: "square",
      vcoMix: 1.0,
      mixerVco1: 1.0,
      filterCutoff: 5000,
      env2Attack: 0.001,
      env2Decay: 0.08,
      env2Sustain: 0,
      delayMix: 0.5,
      delayTime: 0.25,
      delayFeedback: 0.6,
    }
  },
  {
    id: "fx-3",
    name: "Sci-Fi Laser",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vcoMix: 1.0,
      mixerVco1: 1.0,
      filterCutoff: 8000,
      filterEnvAmount: -0.95,
      env1Attack: 0.005,
      env1Decay: 0.35,
      env1Sustain: 0,
      env2Attack: 0.005,
      env2Decay: 0.4,
      env2Sustain: 0,
      portamentoMode: "on",
      portamentoTime: 0.45,
    }
  },
  {
    id: "fx-4",
    name: "Industrial Drone",
    params: {
      ...DEFAULT_PARAMS,
      vco1Waveform: "sawtooth",
      vco2Waveform: "square",
      vco2Sync: true,
      vco2Freq: 5.0,
      vcoMix: 0.4,
      mixerVco1: 0.8,
      mixerVco2: 1.0,
      crossMod: 0.85,
      distortionMix: 0.75,
      distortionAmount: 0.95,
      reverbMix: 0.7,
      reverbTime: 5.0,
    }
  },
  // ARPEGGIOS
  {
    id: "arp-1",
    name: "Neon Pulse",
    params: {
      ...DEFAULT_PARAMS,
      arpEnabled: true,
      arpMode: "up-down",
      arpRate: 140,
      arpRange: 2,
      vco1Waveform: "pulse",
      vco1PulseWidth: 0.2,
      vcoMix: 1.0,
      mixerVco1: 1.0,
      filterCutoff: 1200,
      filterResonance: 0.3,
      filterEnvAmount: 0.4,
      env1Attack: 0.001,
      env1Decay: 0.2,
      env2Attack: 0.001,
      env2Decay: 0.1,
      env2Sustain: 0,
      chorusMix: 0.3,
      delayMix: 0.4,
      delayTime: 0.375, // Dotted 8th-ish
      delayFeedback: 0.4,
      reverbMix: 0.3,
    }
  },
  {
    id: "arp-2",
    name: "Chasing Shadows",
    params: {
      ...DEFAULT_PARAMS,
      arpEnabled: true,
      arpMode: "down",
      arpRate: 200,
      arpRange: 3,
      vco1Waveform: "sawtooth",
      vco2Waveform: "pulse",
      vco2Detune: 0.05,
      vcoMix: 0.5,
      mixerVco1: 0.8,
      mixerVco2: 0.8,
      filterCutoff: 600,
      filterResonance: 0.4,
      env2Attack: 0.005,
      env2Decay: 0.15,
      env2Sustain: 0,
      chorusMix: 0.5,
      delayMix: 0.6,
      delayTime: 0.5,
      delayFeedback: 0.7,
      reverbMix: 0.5,
      reverbTime: 4.0,
    }
  },
  {
    id: "arp-3",
    name: "Stellar Journey",
    params: {
      ...DEFAULT_PARAMS,
      arpEnabled: true,
      arpMode: "random",
      arpRate: 400,
      arpRange: 4,
      vco1Waveform: "sine",
      vco2Waveform: "sine",
      vco2Range: 4,
      vcoMix: 0.5,
      mixerVco1: 0.8,
      mixerVco2: 0.8,
      filterCutoff: 4000,
      filterResonance: 0.1,
      env2Attack: 0.01,
      env2Decay: 0.4,
      env2Sustain: 0,
      chorusMix: 0.7,
      reverbMix: 0.9,
      reverbTime: 8.0,
      lfoRate: 0.2,
      filterLfoAmount: 0.3,
    }
  },
  {
    id: "arp-4",
    name: "Glitchy Circuits",
    params: {
      ...DEFAULT_PARAMS,
      arpEnabled: true,
      arpMode: "up",
      arpRate: 800,
      arpRange: 1,
      vco1Waveform: "square",
      vco2Waveform: "noise",
      vcoMix: 0.7,
      mixerVco1: 1.0,
      mixerVco2: 0.3,
      filterCutoff: 2500,
      filterResonance: 0.6,
      distortionMix: 0.4,
      distortionAmount: 0.7,
      delayMix: 0.5,
      delayTime: 0.1,
      delayFeedback: 0.3,
      env2Attack: 0.001,
      env2Decay: 0.05,
      reverbMix: 0.2,
    }
  },
  {
    id: "arp-5",
    name: "Digital Sunrise",
    params: {
      ...DEFAULT_PARAMS,
      arpEnabled: true,
      arpMode: "up-down",
      arpRate: 300,
      arpRange: 3,
      vco1Waveform: "sawtooth",
      vco2Waveform: "square",
      vco2Freq: 0.05,
      vcoMix: 0.5,
      mixerVco1: 0.7,
      mixerVco2: 0.7,
      filterCutoff: 1500,
      filterResonance: 0.5,
      filterEnvAmount: 0.6,
      env1Attack: 0.01,
      env1Decay: 0.2,
      env2Attack: 0.001,
      env2Decay: 0.1,
      chorusMix: 0.4,
      reverbMix: 0.6,
      delayMix: 0.3,
      delayTime: 0.25,
    }
  },
  {
    id: "arp-6",
    name: "Techno Hammer",
    params: {
      ...DEFAULT_PARAMS,
      arpEnabled: true,
      arpMode: "down",
      arpRate: 120,
      arpRange: 2,
      vco1Waveform: "pulse",
      vco1PulseWidth: 0.5,
      vcoMix: 1.0,
      mixerVco1: 1.0,
      filterCutoff: 250,
      filterResonance: 0.2,
      filterEnvAmount: 0.8,
      env1Attack: 0.001,
      env1Decay: 0.4,
      env2Attack: 0.001,
      env2Decay: 0.1,
      distortionMix: 0.5,
      distortionAmount: 0.8,
      delayMix: 0.2,
      delayTime: 0.375,
    }
  },
  {
    id: "arp-7",
    name: "Ethereal Arps",
    params: {
      ...DEFAULT_PARAMS,
      arpEnabled: true,
      arpMode: "up",
      arpRate: 500,
      arpRange: 4,
      vco1Waveform: "triangle",
      vco2Waveform: "sine",
      vcoMix: 0.5,
      mixerVco1: 0.9,
      mixerVco2: 0.9,
      filterCutoff: 5000,
      filterResonance: 0.0,
      env2Attack: 0.02,
      env2Decay: 0.6,
      chorusMix: 0.8,
      reverbMix: 1.0,
      reverbTime: 9.0,
      delayMix: 0.7,
      delayTime: 0.75,
      delayFeedback: 0.8,
    }
  },
  {
    id: "arp-8",
    name: "Retro Arp 1984",
    params: {
      ...DEFAULT_PARAMS,
      arpEnabled: true,
      arpMode: "up-down",
      arpRate: 250,
      arpRange: 2,
      vco1Waveform: "square",
      vcoMix: 1.0,
      mixerVco1: 1.0,
      filterCutoff: 1800,
      filterResonance: 0.1,
      env2Attack: 0.001,
      env2Decay: 0.2,
      chorusMix: 0.9,
      chorusMode: 2,
      reverbMix: 0.3,
    }
  }
];
